#!/bin/sh
set -e

if [ -n "$SSHPWD" ];
then
        echo "root:$SSHPWD" | chpasswd
fi

if [ -n "$SSHENABLED" ];
then
        echo "Starting sshd"
        /usr/sbin/sshd
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- apache2-foreground "$@"
fi

echo "Starting: $@"

exec "$@"
