#!/bin/sh
set -e

: ${TYPO3_CONTEXT=""}
: ${SSHPWD=""}
: ${SSHENABLED=""}

if [ "$SSHPWD" != "" ]; then
    echo "root:$SSHPWD" | chpasswd
fi

if [ "$SSHENABLED" != "" ]; then
    echo "Starting sshd"
    /usr/sbin/sshd
fi

if [ "$TYPO3_CONTEXT" != "" ]; then
    echo "export TYPO3_CONTEXT=$TYPO3_CONTEXT" >> ~/.profile;
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- apache2-foreground "$@"
fi

echo "Starting: $@"

exec "$@"
